### ISSUE TITLE
ioBroker Ekey adapter error

### ISSUE THREAD

**Issue by Maximilian4711** [ioBroker/ioBroker.ekey#3]
I´m integrating Ekey-Multi-central via CV-Lan (192.168.2.250) to iobroker (192.168.2.223).
Ekey Adapter Version 1.0.0.

Ekey support told that for Multi-Central connection to CV-Lan data format MULTI is mandatory. Raw/Rare doesn´t work.

MULTI format uses strings with separator as data format. I used default configured separator _ .
Documentation says that user-name can be 10 characters max.

The problem:
If user-name is directly included between separators data points are correctly fed.
If there is a blank appended to user-name before separator data points are shifted and incomplete.

IMO adapter should be able to cope with a blank after user-name.
Appended pics show those diverging data point results.

I used Windows software packet-sender (192.168.2.118) to create UDP data strings and for display of CV Lan data strings.

Please help.

More details can be found at 
ioBroker forum at https://forum.iobroker.net/viewtopic.php?p=206516#p206516

![log-fp](https://user-images.githubusercontent.com/33424802/50316095-919ba880-04b5-11e9-8164-fd70c3b194f2.jpg)
![log-packet](https://user-images.githubusercontent.com/33424802/50316096-919ba880-04b5-11e9-9017-c444267d4fa7.jpg)
![obj-packet-fp](https://user-images.githubusercontent.com/33424802/50316097-92343f00-04b5-11e9-9d4a-c953a50abf5a.jpg)
![packet](https://user-images.githubusercontent.com/33424802/50316098-92343f00-04b5-11e9-8ff7-b83807c56334.jpg)

**Comment by GermanBluefox** [comment]
Fixed in 1.1.0
